# DependaTEA yapılandırma dosyası
enabled: true
registry: https://registry.tea.xyz
cache_dir: ~/.tea
log_level: info

environments:
  production:
    node: 18.x
    npm: 9.x
    
  development:
    node: 16.x
    npm: 8.x

priorities:
  - npm
  - yarn
  - tea
